/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRebalancerFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "feeCollector"
      | "feeRate"
      | "getMinOut"
      | "hasOracle"
      | "isRouterAllowed"
      | "maxSlippageCeilingBps"
      | "operator"
      | "paused"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMinOut",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOracle",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRouterAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSlippageCeilingBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMinOut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRouterAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSlippageCeilingBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
}

export interface IRebalancerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IRebalancerFactory;
  waitForDeployment(): Promise<this>;

  interface: IRebalancerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  feeCollector: TypedContractMethod<[], [string], "view">;

  feeRate: TypedContractMethod<[], [bigint], "view">;

  getMinOut: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      maxSlippageBps: BigNumberish
    ],
    [bigint],
    "view"
  >;

  hasOracle: TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [boolean],
    "view"
  >;

  isRouterAllowed: TypedContractMethod<
    [router: AddressLike],
    [boolean],
    "view"
  >;

  maxSlippageCeilingBps: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinOut"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      maxSlippageBps: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasOracle"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRouterAllowed"
  ): TypedContractMethod<[router: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxSlippageCeilingBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
