/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockAggregator,
  MockAggregatorInterface,
} from "../../../../contracts/noncustodial/mocks/MockAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_decimals",
        type: "uint8",
      },
      {
        internalType: "int256",
        name: "_answer",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "answer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_answer",
        type: "int256",
      },
    ],
    name: "setAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_updatedAt",
        type: "uint256",
      },
    ],
    name: "setUpdatedAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updatedAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a03461007157601f61021638819003918201601f19168301916001600160401b038311848410176100765780849260409485528339810103126100715780519060ff8216820361007157602001519060805260005542600155604051610189908161008d8239608051816101100152f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe608080604052600436101561001357600080fd5b600090813560e01c9081631ecc7d8814610138578163313ce567146100f7575080637519ab50146100d957806385bb7d69146100bc57806399213cd81461009e5763feaf968c1461006357600080fd5b3461009b578060031936011261009b5760a0905460015460405191600183526020830152806040830152606082015260016080820152f35b80fd5b503461009b57602036600319011261009b5760043581554260015580f35b503461009b578060031936011261009b5760209054604051908152f35b503461009b578060031936011261009b576020600154604051908152f35b90503461013457816003193601126101345760209060ff7f0000000000000000000000000000000000000000000000000000000000000000168152f35b5080fd5b823461009b57602036600319011261009b5760043560015580f3fea2646970667358221220aaac2aac89412ae97d0e0bbe93eab5796f61e0e79b08bf2186717233bc815d2a64736f6c63430008180033";

type MockAggregatorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAggregatorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAggregator__factory extends ContractFactory {
  constructor(...args: MockAggregatorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _decimals: BigNumberish,
    _answer: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_decimals, _answer, overrides || {});
  }
  override deploy(
    _decimals: BigNumberish,
    _answer: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_decimals, _answer, overrides || {}) as Promise<
      MockAggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAggregator__factory {
    return super.connect(runner) as MockAggregator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAggregatorInterface {
    return new Interface(_abi) as MockAggregatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAggregator {
    return new Contract(address, _abi, runner) as unknown as MockAggregator;
  }
}
