/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BUDGET_WINDOW"
      | "agentTrade"
      | "budgets"
      | "canTrade"
      | "deposit"
      | "factory"
      | "initialize"
      | "owner"
      | "permissions"
      | "remainingBudget"
      | "revokeAgentPair"
      | "setAgentBudget"
      | "setAgentPermission"
      | "transferOwnership"
      | "withdraw"
      | "withdrawAll"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentBudgetSet"
      | "AgentPermissionSet"
      | "AgentRevoked"
      | "AgentTraded"
      | "Deposited"
      | "Initialized(uint64)"
      | "Initialized(address,address)"
      | "OwnershipTransferred"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BUDGET_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentTrade",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "budgets",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTrade",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permissions",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingBudget",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAgentPair",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentBudget",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentPermission",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BUDGET_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "budgets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgentPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
}

export namespace AgentBudgetSetEvent {
  export type InputTuple = [
    agent: AddressLike,
    token: AddressLike,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [agent: string, token: string, dailyLimit: bigint];
  export interface OutputObject {
    agent: string;
    token: string;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentPermissionSetEvent {
  export type InputTuple = [
    agent: AddressLike,
    from: AddressLike,
    to: AddressLike,
    enabled: boolean,
    maxSlippageBps: BigNumberish,
    expiresAt: BigNumberish,
    maxNotional: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    from: string,
    to: string,
    enabled: boolean,
    maxSlippageBps: bigint,
    expiresAt: bigint,
    maxNotional: bigint
  ];
  export interface OutputObject {
    agent: string;
    from: string;
    to: string;
    enabled: boolean;
    maxSlippageBps: bigint;
    expiresAt: bigint;
    maxNotional: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentTradedEvent {
  export type InputTuple = [
    agent: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amountIn: BigNumberish,
    netOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    from: string,
    to: string,
    amountIn: bigint,
    netOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    agent: string;
    from: string;
    to: string;
    amountIn: bigint;
    netOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, from: string, amount: bigint];
  export interface OutputObject {
    token: string;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Initialized_uint64_Event {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Initialized_address_address_Event {
  export type InputTuple = [owner: AddressLike, factory: AddressLike];
  export type OutputTuple = [owner: string, factory: string];
  export interface OutputObject {
    owner: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVault extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVault;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BUDGET_WINDOW: TypedContractMethod<[], [bigint], "view">;

  agentTrade: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      router: AddressLike,
      swapData: BytesLike,
      agentMinOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  budgets: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        dailyLimit: bigint;
        spentInWindow: bigint;
        windowStart: bigint;
      }
    ],
    "view"
  >;

  canTrade: TypedContractMethod<
    [
      agent: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish
    ],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_owner: AddressLike, _factory: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  permissions: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, boolean] & {
        enabled: boolean;
        maxSlippageBps: bigint;
        cooldown: bigint;
        lastExec: bigint;
        expiresAt: bigint;
        maxNotional: bigint;
        trustAgentMinOut: boolean;
      }
    ],
    "view"
  >;

  remainingBudget: TypedContractMethod<
    [agent: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  revokeAgentPair: TypedContractMethod<
    [agent: AddressLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentBudget: TypedContractMethod<
    [agent: AddressLike, token: AddressLike, dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAgentPermission: TypedContractMethod<
    [
      agent: AddressLike,
      from: AddressLike,
      to: AddressLike,
      enabled: boolean,
      maxSlippageBps: BigNumberish,
      cooldown: BigNumberish,
      expiresAt: BigNumberish,
      maxNotional: BigNumberish,
      trustAgentMinOut: boolean
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawAll: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BUDGET_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentTrade"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      router: AddressLike,
      swapData: BytesLike,
      agentMinOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "budgets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        dailyLimit: bigint;
        spentInWindow: bigint;
        windowStart: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "canTrade"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish
    ],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_owner: AddressLike, _factory: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permissions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, boolean] & {
        enabled: boolean;
        maxSlippageBps: bigint;
        cooldown: bigint;
        lastExec: bigint;
        expiresAt: bigint;
        maxNotional: bigint;
        trustAgentMinOut: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "remainingBudget"
  ): TypedContractMethod<
    [agent: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeAgentPair"
  ): TypedContractMethod<
    [agent: AddressLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentBudget"
  ): TypedContractMethod<
    [agent: AddressLike, token: AddressLike, dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentPermission"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      from: AddressLike,
      to: AddressLike,
      enabled: boolean,
      maxSlippageBps: BigNumberish,
      cooldown: BigNumberish,
      expiresAt: BigNumberish,
      maxNotional: BigNumberish,
      trustAgentMinOut: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAll"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentBudgetSet"
  ): TypedContractEvent<
    AgentBudgetSetEvent.InputTuple,
    AgentBudgetSetEvent.OutputTuple,
    AgentBudgetSetEvent.OutputObject
  >;
  getEvent(
    key: "AgentPermissionSet"
  ): TypedContractEvent<
    AgentPermissionSetEvent.InputTuple,
    AgentPermissionSetEvent.OutputTuple,
    AgentPermissionSetEvent.OutputObject
  >;
  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AgentTraded"
  ): TypedContractEvent<
    AgentTradedEvent.InputTuple,
    AgentTradedEvent.OutputTuple,
    AgentTradedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized(uint64)"
  ): TypedContractEvent<
    Initialized_uint64_Event.InputTuple,
    Initialized_uint64_Event.OutputTuple,
    Initialized_uint64_Event.OutputObject
  >;
  getEvent(
    key: "Initialized(address,address)"
  ): TypedContractEvent<
    Initialized_address_address_Event.InputTuple,
    Initialized_address_address_Event.OutputTuple,
    Initialized_address_address_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentBudgetSet(address,address,uint128)": TypedContractEvent<
      AgentBudgetSetEvent.InputTuple,
      AgentBudgetSetEvent.OutputTuple,
      AgentBudgetSetEvent.OutputObject
    >;
    AgentBudgetSet: TypedContractEvent<
      AgentBudgetSetEvent.InputTuple,
      AgentBudgetSetEvent.OutputTuple,
      AgentBudgetSetEvent.OutputObject
    >;

    "AgentPermissionSet(address,address,address,bool,uint16,uint64,uint128)": TypedContractEvent<
      AgentPermissionSetEvent.InputTuple,
      AgentPermissionSetEvent.OutputTuple,
      AgentPermissionSetEvent.OutputObject
    >;
    AgentPermissionSet: TypedContractEvent<
      AgentPermissionSetEvent.InputTuple,
      AgentPermissionSetEvent.OutputTuple,
      AgentPermissionSetEvent.OutputObject
    >;

    "AgentRevoked(address)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "AgentTraded(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      AgentTradedEvent.InputTuple,
      AgentTradedEvent.OutputTuple,
      AgentTradedEvent.OutputObject
    >;
    AgentTraded: TypedContractEvent<
      AgentTradedEvent.InputTuple,
      AgentTradedEvent.OutputTuple,
      AgentTradedEvent.OutputObject
    >;

    "Deposited(address,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      Initialized_uint64_Event.InputTuple,
      Initialized_uint64_Event.OutputTuple,
      Initialized_uint64_Event.OutputObject
    >;
    "Initialized(address,address)": TypedContractEvent<
      Initialized_address_address_Event.InputTuple,
      Initialized_address_address_Event.OutputTuple,
      Initialized_address_address_Event.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
