/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentVaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allVaults"
      | "configFactory"
      | "deployAgentVault"
      | "implementation"
      | "vaultOf"
      | "vaultsCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AgentVaultDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployAgentVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultsCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAgentVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultsCount",
    data: BytesLike
  ): Result;
}

export namespace AgentVaultDeployedEvent {
  export type InputTuple = [user: AddressLike, vault: AddressLike];
  export type OutputTuple = [user: string, vault: string];
  export interface OutputObject {
    user: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  configFactory: TypedContractMethod<[], [string], "view">;

  deployAgentVault: TypedContractMethod<[], [string], "nonpayable">;

  implementation: TypedContractMethod<[], [string], "view">;

  vaultOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  vaultsCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "configFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployAgentVault"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "vaultsCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AgentVaultDeployed"
  ): TypedContractEvent<
    AgentVaultDeployedEvent.InputTuple,
    AgentVaultDeployedEvent.OutputTuple,
    AgentVaultDeployedEvent.OutputObject
  >;

  filters: {
    "AgentVaultDeployed(address,address)": TypedContractEvent<
      AgentVaultDeployedEvent.InputTuple,
      AgentVaultDeployedEvent.OutputTuple,
      AgentVaultDeployedEvent.OutputObject
    >;
    AgentVaultDeployed: TypedContractEvent<
      AgentVaultDeployedEvent.InputTuple,
      AgentVaultDeployedEvent.OutputTuple,
      AgentVaultDeployedEvent.OutputObject
    >;
  };
}
