/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  MockRouter,
  MockRouterInterface,
} from "../../../../../contracts/noncustodial/mocks/MockRouter.sol/MockRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576101bd908161001c8239f35b600080fdfe608060408181526004908136101561001657600080fd5b600091823560e01c63d5bcb9b51461002d57600080fd5b346101835760a0366003190112610183576001600160a01b03813581811690819003610110576024359082821680920361015a5760843592831680930361015a5786606481886020946323b872dd60e01b8352338984015230602484015260443560448401525af1801561017957610114575b849550803b156101105760448592855196879384926340c10f1960e01b84528784015260643560248401525af18015610106576100db578380f35b67ffffffffffffffff83116100f35750523880808380f35b634e487b7160e01b845260419052602483fd5b82513d86823e3d90fd5b8480fd5b6020953d602011610171575b601f8701601f1916810167ffffffffffffffff81118282101761015e5781879860209288528101031261015a5751801515146100a0578480fd5b8580fd5b634e487b7160e01b875260418552602487fd5b3d9650610120565b84513d87823e3d90fd5b8280fdfea264697066735822122037a690c1f13e528ed3409b9122b36143ad5dbde2a434e6977046f3c36fdc5f4e64736f6c63430008180033";

type MockRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRouter__factory extends ContractFactory {
  constructor(...args: MockRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockRouter__factory {
    return super.connect(runner) as MockRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRouterInterface {
    return new Interface(_abi) as MockRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockRouter {
    return new Contract(address, _abi, runner) as unknown as MockRouter;
  }
}
