/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockRouterSol from "./MockRouter.sol";
export type { mockRouterSol };
export type { MockAggregator } from "./MockAggregator";
export type { MockERC20 } from "./MockERC20";
export type { MockERC20Permit } from "./MockERC20Permit";
export type { MockV3Pool } from "./MockV3Pool";
