/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RebalancerFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "MAX_FEE_RATE"
      | "MIN_TWAP_PERIOD"
      | "allVaults"
      | "deployVault"
      | "feeCollector"
      | "feeRate"
      | "getMinOut"
      | "hasOracle"
      | "implementation"
      | "isRouterAllowed"
      | "maxPriceAge"
      | "maxSlippageCeilingBps"
      | "operator"
      | "owner"
      | "paused"
      | "priceFeeds"
      | "priceMaxAge"
      | "renounceOwnership"
      | "setFee"
      | "setOperator"
      | "setParams"
      | "setPaused"
      | "setPriceFeed"
      | "setRouterAllowed"
      | "setTwapPool"
      | "transferOwnership"
      | "twapPools"
      | "vaultOf"
      | "vaultsCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "ParamsUpdated"
      | "PausedSet"
      | "PriceFeedUpdated"
      | "RouterUpdated"
      | "TwapPoolUpdated"
      | "VaultDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TWAP_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMinOut",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOracle",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRouterAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSlippageCeilingBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceFeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceMaxAge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouterAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTwapPool",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "twapPools",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultsCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TWAP_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMinOut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRouterAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSlippageCeilingBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceMaxAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRouterAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTwapPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "twapPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultsCount",
    data: BytesLike
  ): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [rate: BigNumberish, collector: AddressLike];
  export type OutputTuple = [rate: bigint, collector: string];
  export interface OutputObject {
    rate: bigint;
    collector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [oldOp: AddressLike, newOp: AddressLike];
  export type OutputTuple = [oldOp: string, newOp: string];
  export interface OutputObject {
    oldOp: string;
    newOp: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParamsUpdatedEvent {
  export type InputTuple = [
    maxSlippageCeilingBps: BigNumberish,
    maxPriceAge: BigNumberish
  ];
  export type OutputTuple = [
    maxSlippageCeilingBps: bigint,
    maxPriceAge: bigint
  ];
  export interface OutputObject {
    maxSlippageCeilingBps: bigint;
    maxPriceAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedSetEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFeedUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    feed: AddressLike,
    maxAge: BigNumberish
  ];
  export type OutputTuple = [token: string, feed: string, maxAge: bigint];
  export interface OutputObject {
    token: string;
    feed: string;
    maxAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterUpdatedEvent {
  export type InputTuple = [router: AddressLike, allowed: boolean];
  export type OutputTuple = [router: string, allowed: boolean];
  export interface OutputObject {
    router: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TwapPoolUpdatedEvent {
  export type InputTuple = [
    tokenA: AddressLike,
    tokenB: AddressLike,
    pool: AddressLike,
    period: BigNumberish
  ];
  export type OutputTuple = [
    tokenA: string,
    tokenB: string,
    pool: string,
    period: bigint
  ];
  export interface OutputObject {
    tokenA: string;
    tokenB: string;
    pool: string;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultDeployedEvent {
  export type InputTuple = [user: AddressLike, vault: AddressLike];
  export type OutputTuple = [user: string, vault: string];
  export interface OutputObject {
    user: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RebalancerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): RebalancerFactory;
  waitForDeployment(): Promise<this>;

  interface: RebalancerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  MIN_TWAP_PERIOD: TypedContractMethod<[], [bigint], "view">;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deployVault: TypedContractMethod<[], [string], "nonpayable">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  feeRate: TypedContractMethod<[], [bigint], "view">;

  getMinOut: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      maxSlippageBps: BigNumberish
    ],
    [bigint],
    "view"
  >;

  hasOracle: TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [boolean],
    "view"
  >;

  implementation: TypedContractMethod<[], [string], "view">;

  isRouterAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  maxPriceAge: TypedContractMethod<[], [bigint], "view">;

  maxSlippageCeilingBps: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  priceFeeds: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  priceMaxAge: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFee: TypedContractMethod<
    [_feeRate: BigNumberish, _feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [_operator: AddressLike],
    [void],
    "nonpayable"
  >;

  setParams: TypedContractMethod<
    [_maxSlippageCeilingBps: BigNumberish, _maxPriceAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  setPriceFeed: TypedContractMethod<
    [token: AddressLike, feed: AddressLike, maxAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRouterAllowed: TypedContractMethod<
    [router: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setTwapPool: TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      pool: AddressLike,
      period: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  twapPools: TypedContractMethod<
    [arg0: BytesLike],
    [[string, bigint] & { pool: string; period: bigint }],
    "view"
  >;

  vaultOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  vaultsCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TWAP_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deployVault"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinOut"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amountIn: BigNumberish,
      maxSlippageBps: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasOracle"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isRouterAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxPriceAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSlippageCeilingBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceFeeds"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "priceMaxAge"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<
    [_feeRate: BigNumberish, _feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[_operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setParams"
  ): TypedContractMethod<
    [_maxSlippageCeilingBps: BigNumberish, _maxPriceAge: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceFeed"
  ): TypedContractMethod<
    [token: AddressLike, feed: AddressLike, maxAge: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRouterAllowed"
  ): TypedContractMethod<
    [router: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTwapPool"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      pool: AddressLike,
      period: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "twapPools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, bigint] & { pool: string; period: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "vaultsCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParamsUpdated"
  ): TypedContractEvent<
    ParamsUpdatedEvent.InputTuple,
    ParamsUpdatedEvent.OutputTuple,
    ParamsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PausedSet"
  ): TypedContractEvent<
    PausedSetEvent.InputTuple,
    PausedSetEvent.OutputTuple,
    PausedSetEvent.OutputObject
  >;
  getEvent(
    key: "PriceFeedUpdated"
  ): TypedContractEvent<
    PriceFeedUpdatedEvent.InputTuple,
    PriceFeedUpdatedEvent.OutputTuple,
    PriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RouterUpdated"
  ): TypedContractEvent<
    RouterUpdatedEvent.InputTuple,
    RouterUpdatedEvent.OutputTuple,
    RouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TwapPoolUpdated"
  ): TypedContractEvent<
    TwapPoolUpdatedEvent.InputTuple,
    TwapPoolUpdatedEvent.OutputTuple,
    TwapPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultDeployed"
  ): TypedContractEvent<
    VaultDeployedEvent.InputTuple,
    VaultDeployedEvent.OutputTuple,
    VaultDeployedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256,address)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "OperatorUpdated(address,address)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParamsUpdated(uint16,uint256)": TypedContractEvent<
      ParamsUpdatedEvent.InputTuple,
      ParamsUpdatedEvent.OutputTuple,
      ParamsUpdatedEvent.OutputObject
    >;
    ParamsUpdated: TypedContractEvent<
      ParamsUpdatedEvent.InputTuple,
      ParamsUpdatedEvent.OutputTuple,
      ParamsUpdatedEvent.OutputObject
    >;

    "PausedSet(bool)": TypedContractEvent<
      PausedSetEvent.InputTuple,
      PausedSetEvent.OutputTuple,
      PausedSetEvent.OutputObject
    >;
    PausedSet: TypedContractEvent<
      PausedSetEvent.InputTuple,
      PausedSetEvent.OutputTuple,
      PausedSetEvent.OutputObject
    >;

    "PriceFeedUpdated(address,address,uint256)": TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;
    PriceFeedUpdated: TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;

    "RouterUpdated(address,bool)": TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;
    RouterUpdated: TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;

    "TwapPoolUpdated(address,address,address,uint32)": TypedContractEvent<
      TwapPoolUpdatedEvent.InputTuple,
      TwapPoolUpdatedEvent.OutputTuple,
      TwapPoolUpdatedEvent.OutputObject
    >;
    TwapPoolUpdated: TypedContractEvent<
      TwapPoolUpdatedEvent.InputTuple,
      TwapPoolUpdatedEvent.OutputTuple,
      TwapPoolUpdatedEvent.OutputObject
    >;

    "VaultDeployed(address,address)": TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
    VaultDeployed: TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
  };
}
