"""Policy violation codes and constants."""

# Violation codes
MAX_SLIPPAGE_BPS = "MAX_SLIPPAGE_BPS"
MAX_GAS_USD = "MAX_GAS_USD"
MIN_LIQUIDITY_SCORE = "MIN_LIQUIDITY_SCORE"
MIN_EDGE_AFTER_COST_BPS = "MIN_EDGE_AFTER_COST_BPS"
MAX_TRADE_PCT_OF_BALANCE = "MAX_TRADE_PCT_OF_BALANCE"
COOLDOWN_MINUTES = "COOLDOWN_MINUTES"
MAX_DAILY_TURNOVER_PCT = "MAX_DAILY_TURNOVER_PCT"
DATA_STALENESS_SECONDS = "DATA_STALENESS_SECONDS"
TOKEN_DENIED = "TOKEN_DENIED"

# Severity levels
BLOCK = "BLOCK"
WARN = "WARN"
